apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: generate
  namespace: jenkins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: generate
subjects:
- kind: ServiceAccount
  name: generate
  namespace: jenkins
