FROM ubuntu:18.04

RUN apt-get update && apt-get install -y curl

ARG HELM_VERSION
RUN curl -LO "https://get.helm.sh/helm-v${HELM_VERSION}-linux-amd64.tar.gz" && \
  tar xvf "helm-v${HELM_VERSION}-linux-amd64.tar.gz" && \
  chmod 755 linux-amd64/helm && \
  mv linux-amd64/helm /usr/local/bin && \
  rm -r linux-amd64

WORKDIR /workspace

ENTRYPOINT ["/usr/local/bin/helm"]
