FROM ubuntu:18.04

RUN apt-get update && apt-get install -y curl

ARG KFMT_VERSION
RUN curl -LO "https://github.com/dippynark/kfmt/releases/download/v${KFMT_VERSION}/kfmt-linux-amd64" && \
  chmod +x kfmt-linux-amd64 && \
  mv kfmt-linux-amd64 /usr/local/bin/kfmt

WORKDIR /workspace

ENTRYPOINT ["/usr/local/bin/kfmt"]
