FROM ubuntu:18.04

RUN apt-get update && apt-get install -y curl

ARG YQ_VERSION
RUN curl -L -o yq "https://github.com/mikefarah/yq/releases/download/v${YQ_VERSION}/yq_linux_amd64" && \
  chmod 755 ./yq && \
  mv yq /usr/local/bin

WORKDIR /workspace

ENTRYPOINT ["/usr/local/bin/yq"]
