FROM golang:1.15.4 as builder

WORKDIR /workspace

ARG KFMT_VERSION
RUN git clone https://github.com/dippynark/kfmt && \
  cd kfmt && git checkout "${KFMT_VERSION}"
RUN cd kfmt && go mod download
RUN cd kfmt && CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -o kfmt

FROM ubuntu:18.04

COPY --from=builder /workspace/kfmt/kfmt /usr/local/bin/kfmt

WORKDIR /workspace

ENTRYPOINT ["/usr/local/bin/kfmt"]
