apiVersion: v1
kind: Secret
metadata:
  name: tekton-container-registry-auth
  namespace: lighthouse
  annotations:
    tekton.dev/docker-0: https://docker.io
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson:
